### ISSUE TITLE
Dependency detection fails with previously declared var

### ISSUE THREAD

**Issue by bendrucker** [thlorenz/proxyquireify#25]
Currently you can't do:

```js
var p;
p = require('proxyquireify')(require)
```

Aside from being perfectly valid JS, this is the output derived from compiling CoffeeScript

**Comment by alanrubin** [comment]
+1 for this one. That will make sure CoffeeScript can use proxyquireify. 

The question is should we support this case as well ?
```
var p;
p = require('proxyquireify')
```
The inline assignment is currently being tested in code so I assume we should test this form as well.

**Comment by bendrucker** [comment]
Yes, see #27. Feel free to pick up where I left off and open a new PR.
