### ISSUE TITLE
Restrict peerDep

### ISSUE THREAD

**Issue by bendrucker** [thlorenz/proxyquireify#30]
proxyquireify does a whole lot more than something like b-shim so it probably shouldn't be a >= peerDep with Browserify. @thlorenz are you cool with switching this to the same policy as b-shim, i.e. `>= ${min} < ${currentMajor + 1}`?

**Comment by thlorenz** [comment]
Lets wait tiil we actually get a compat issue. The moment that happens we can fix it and add the peer dep.

**Comment by bendrucker** [comment]
Fair enough. I'm writing up a tool for doing peerDep major version testing that we can use here and with b-shim for automated testing. I'll do PRs here and for b-shim when it's ready.

**Comment by thlorenz** [comment]
Awesome, looking forward to that!
