### ISSUE TITLE
Breaking changes for 3.0.0?

### ISSUE THREAD

**Issue by TheSavior** [thlorenz/proxyquireify#42]
What are the breaking changes that caused the bump to 3.0.0? I don't see release notes or a change log that makes that clear. It wasn't immediately clear by looking through the commit history.

**Comment by bendrucker** [comment]
The call to make it v3 was here: https://github.com/thlorenz/proxyquireify/pull/39#discussion_r35038735

#39 is in some ways a bug fix. Immediately executing every file you pass to proxyquireify as was happening prior to 3.0 is clearly wrong. But with a test utility it can't hurt to be conservative with versioning.
