### ISSUE TITLE
proxyquirefy not in npm repository!

### ISSUE THREAD

**Issue by hayesmaker** [thlorenz/proxyquireify#55]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/proxyquirefy
npm ERR! 404
npm ERR! 404 'proxyquirefy' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'casino-engine'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/npm-debug.log

**Comment by bendrucker** [comment]
Check your spelling
