### ISSUE TITLE
When I left one of the required modules unstubbed, it's not calling the original module

### ISSUE THREAD

**Issue by gsalisi** [thlorenz/proxyquireify#63]
foo.js

```
const bar = require('app/bar.js');
const model = require('./model.js');
```

fooSpec.js

```
const bar = require('app/bar.js');
const proxyquire = require('proxyquireify')(require);
const foo = proxyquire('./foo.js', {
    './model.js': {
        test: 'yay'
    }
});
```

`bar` in `foo.js` is an empty object.
`bar` in `fooSpec.js` is the _correct_ data.
`model` gets mocked to `{ test: 'yay }` properly

Why is it that bar is not calling through properly?

**Comment by bendrucker** [comment]
What's `data`? Can't make sense of your example and exactly what's wrong here. If possible a runnable example is very helpful.

**Comment by gsalisi** [comment]
Sorry about that, I updated the names. I just want to verify that not stubbing a required file actually fetches the original required file. It doesn't seem to work for me.

**Comment by bendrucker** [comment]
`bar.js` isn't a legal require statement unless you have an npm module called `bar.js`. Should be `./bar.js` if it's a local file. Is that it?

**Comment by gsalisi** [comment]
I am requiring a local file. For this case let's pretend it is at `app/js/bar.js`. This is getting stubbed to an empty object instead of using the original require.

**Comment by bendrucker** [comment]
Please update your original example then. It's not valid as is and I can't be sure what's going on if I don't know what you're running. Again, a runnable example is by far the fastest way for us to get you help.

**Comment by gsalisi** [comment]
I am using karma for running the tests with browserify with the following config:

```
config.set({
        basePath : basePath,
        frameworks: [ 'browserify', 'jasmine' ],
        exclude: exclude,
        files: files,
        preprocessors: preprocessors,
        browserify: {
            debug: true,
            plugin: [
                ['remapify', [{
                    src: '**/*.js',
                    expose: appName,
                    cwd: clientRoot + '/' + appName
                }, {
                    src: '**/*.js',
                    expose: 'dxtest',
                    cwd: clientRoot + '/dxtest'
                }, {
                    src: '**/*.js',
                    expose: 'dxcore',
                    cwd: clientRoot + '/dxcore'
                }]],
                'proxyquireify/plugin'
            ],
            transform: [
                ['babelify', {
                    ignore: ['dxcore/lib/**/*.js'],
                    blacklist: ['es6.tailCall']
                }]
            ],
            watch: true
        },
        ...
}

```

If none of this stands out to you as a cause to my issue, feel free to close this ticket and I will opt to not use this library.
To clarify, the issue is it's not calling through unstubbed/uspecified files as expected.

**Comment by bendrucker** [comment]
Ok, I can't really make sense of what's going on. If you can't provide a runnable example it's too hard for me to diagnose.
